#!/bin/sh

# Modified and improved version of Cisco's Script

# If you exprerience any troubles, try to uncomment
# the following line

export LD_LIBRARY_PATH="/usr/share/packettracer/bin"

exec /usr/share/packettracer/bin/PacketTracer7 "$@"

